### ISSUE TITLE
Not an issue - advice please on installing and using

### ISSUE THREAD

**Issue by wisdomlight** [ClosedWontFix/obs2zoom#1]
Hi,
Many thanks for taking the time to create the script.
I am not very confident with scripts etc.
Should I download your script give it the execute permission and run it with ./obs2zoom start 
is that all that needs doing??

Once the script has run, what should I actually be doing??
When I am trying to conect to Jitsi on Firefox I get all these audio options

Monitor of Built in Audio Analog Stereo
Built-in Audio Analog Stereo
Monitor of USB PnP Audio Devcie Analog Stereo
USB PnP Audio Devcie Analog Stereo
Monitor of OBS monitor sink
Monitor of To OBS
Monitor of To OBS(Monitored)
From OBS
Echo Concelled Microphone
Monitor of Echo Concelled Speakers

I am not sure which one to use?
Thank you

**Comment by ClosedWontFix** [comment]
Hi @wisdomlight 

Correct, to execute the script, simply run 'obs2zoom start' though you may have to make it executable first.  This will create the necessary sources and sinks in pulseaudio.  

Then, in obs, go to File->Settings->Audio->Advanced, and select 'Monitor of OBS monitor sink'.  

Next, create a scene, and add the following sources:

- Audio Input Capture (pulseaudio): Name it 'Echo Cancelled Microphone', and select the device with the same name.
- Audio Input Capture (pulseaudio): Name it 'Microphone', and select the physical microphone that you will use for input.
- Audio Output Capture (pulseaudio): Name it 'To OBS', and select the device with the same name.
- Audio Output Capture (pulseaudio): Name it 'To OBS (Monitored)', and select the device with the same name.

Now go to Edit->Advanced Audio Properties, and set the Audio Monitoring like so:

- Echo Cancelled Microphone - Monitor Off
- Microphone - Monitor Only (mute output)
- To OBS - Monitor Off
- To OBS - Monitor and Output

Now all the hard stuff is done.  Open whatever VidConf software you are using, and Select:

- Microphone -> 'Echo Cancelled Microphone' 
- Speakers -> 'Echo Cancelled Speakers'

The README.md is updated with some images that should help.

I have tested this on Webex, Google Meet, Google Duo, MS Teams, BlueJeans, and Signal Desktop.  I assume it should also work on Jitsi.

I hope this helps!

**Comment by wisdomlight** [comment]
Thank you for your comments.
I followed them and there were no issues.
I am not sure that I get the result I hoped for.
I am so confused by audio redirection now ....
I may post some actual question after I've done few more trials.
Thank you for you help

**Comment by davepee** [comment]
Thank you for the useful script:) I also have one small question. On which microphone device on OBS can I add additional filters for video conference participants to hear it? 'Echo Canceled Microphone' or 'Microphone'? Thx so much!

**Comment by ClosedWontFix** [comment]
Glad to hear this is working for you.  

Add your filters to 'Microphone'.  You can see mine below.

![image](https://user-images.githubusercontent.com/12750133/114202913-496e5180-991d-11eb-9d92-8cfc3ec5ed77.png)
